# because of keycloak locally this only works when using the host network which
# is so insanely deranged but hey it works so...

services:
  api:
    image: heofthetea/horsey-go-brrrr-be:jvm-latest
    container_name: horsey-api
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/horsey_api
      QUARKUS_OIDC_AUTH_SERVER_URL: http://localhost:8081/realms/horsey-realm
      QUARKUS_HTTP_PORT: 8085
      QUARKUS_HTTP_CORS_HEADERS: "*"
      QUARKUS_HTTP_CORS_ORIGINS: "*"
      QUARKUS_HTTP_CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
    network_mode: host # necessary for keycloak to not throw issuer-mismatch fits locally
    depends_on:
      - postgres
      - keycloak

  frontend:
    image: heofthetea/horsey-go-brrrr-fe:latest
    container_name: horsey-frontend
    environment:
      HORSEY_API_BASE_URL: http://localhost:8085/api/
      HORSEY_WEBSOCKET_URL: ws://localhost:8085/api/ws
      HORSEY_KEYCLOAK_URL: http://localhost:8081
      HORSEY_KEYCLOAK_REALM: horsey-realm
      HORSEY_KEYCLOAK_CLIENT_ID: horsey-frontend
    networks:
      - horsey-net
    ports:
      - "15173:80"
    depends_on:
      - api
      - postgres

  postgres:
    image: postgres:17.4-bookworm
    container_name: horsey-postgres
    # restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - horsey_pgdata:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d
    networks:
      - horsey-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: horsey-keycloak
    # restart: unless-stopped
    ports:
      - "8081:8081"
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost # lol
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_STRICT=true
      - KC_HTTP_PORT=8081
      - KC_DB_URL=jdbc:postgresql://horsey-postgres:5432/horsey_keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_DB=postgres
    networks:
      - horsey-net

    depends_on:
      - postgres

volumes:
  horsey_pgdata:

networks:
  horsey-net:
